apiVersion: v1
kind: Service
metadata:
  name: frontend-app-svc
  namespace: default
  labels:
    app: frontend-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30036
  selector:
    app: frontend-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: default
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
#      imagePullSecrets:
#      - name: ap-southeast-1-ecr-registry
#      nodeSelector:
#        prod: frontend
#      tolerations:
#      - key: "prod"
#        operator: "Equal"
#        value: "frontend"
#        effect: "NoSchedule"
      containers:
      - name: frontend-app
        image: frontend-task/get-user-name:latest
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5 
          periodSeconds: 30
          failureThreshold: 3 
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 30
          failureThreshold: 3
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 80
