apiVersion: v1
kind: Service
metadata:
  name: fe-app
  namespace: default
  labels:
    app: fe-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30036
  selector:
    app: fe-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-app
  namespace: default
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
      labels:
        app: fe-app
    spec:
#      imagePullSecrets:
#      - name: ap-southeast-1-ecr-registry
      containers:
      - name: fe-app
        image: viraj/fe-get-user-name:latest
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5 
          periodSeconds: 30
          failureThreshold: 3 
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 30
          failureThreshold: 3
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 80
